name: Github Pages
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'masapasa'
        required: true
      email:
        description: 'apyakurel@gmail.com'
        required: true

jobs:
  Deploy-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Login
        run: git config --global user.name "${{github.event.inputs.username}}" && git config --global user.email "${{github.event.inputs.email}}"

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: yarn install

      - name: Deploy
        run: yarn push:build
